FROM thewtex/krs-course:local

RUN python -m pip install git+https://github.com/data-8/nbgitpuller && \
  python -m jupyter serverextension enable --py nbgitpuller --sys-prefix
CMD ["/usr/local/bin/start-singleuser.sh"]
