FROM thewtex/krs-course:local

RUN python -m pip install git+https://github.com/data-8/nbgitpuller && \
  python -m jupyter serverextension enable --py nbgitpuller --sys-prefix

ADD LICENSE /home/jovyan/
ADD *.ipynb /home/jovyan/
ADD data /home/jovyan/data
USER root
RUN chown -R $NB_USER:users /home/jovyan/*
USER $NB_USER
RUN rmdir /home/jovyan/work

CMD ["/usr/local/bin/start-singleuser.sh"]
